### ISSUE TITLE
Prepare for upgrade to RDF2

### ISSUE THREAD

**Issue by hackmastera** [chemheritage/chf-sufia#235]
Current versions of our upstream codebases depend on RDF2 which takes away the ordering guarantee (since RDF is explicitly non-ordered, the maintainer of that gem decided to get rid of ordering in favor of performance improvements).

This means data entries in any metadata field with multiple entries may be presented in any order. Where this will be an issue, we should either:

1. adjust our model, e.g. use `preferred_title` and `alternate_titles` instead of just `title`.
2. Default to an alphabetical sort.

To implement true ordering would be complex and make things slower, however it is possible if required.

Preliminary discussion indicates that title is the primary concern. Other fields should be fine with alphasort.

@catlu I think we've discussed description as a potential issue in the past?

child tickets:

- [x] https://github.com/chemheritage/chf-sufia/issues/244
- [x] https://github.com/chemheritage/chf-sufia/issues/247
- [x] #320 
- [x] #321 
- [x] https://github.com/chemheritage/chf-sufia/issues/245
- [x] https://github.com/chemheritage/chf-sufia/issues/246

**Comment by catlu** [comment]
@hackmastera yep, I'm thinking description would be a case like preferred/alternate, or making it non-repeatable? I've gotten feedback that curators have found the repeatable description field confusing.

**Comment by hackmastera** [comment]
required for upgrade to active fedora 11

**Comment by MDiMeo** [comment]
Curators agreed to drop current order of collections and preferred alpha-sort or model changes discussed in DCC meeting on Dec. 2 2016: https://chemheritage.atlassian.net/wiki/display/HDC/DCC+Minutes+2016.12.2 

- I emailed Stephanie and Gillian personal emails regarding Museum object concerns on Jan. 30 and got a positive response from Stephanie (cc'd Gillian) on Jan. 31.
- I emailed Dave and Lee personal emails regarding Oral History object concerns on Jan. 30 and got a positive response from each of them on Jan. 30 (Lee) and Jan. 31 (Dave).
- I emailed the DCC to follow-up on Jan. 31 and asked for responses by Feb. 3. I received positive responses from Patrick (Jan. 31) and Hillary (Feb. 1). No one else responded, and the email clearly said that no response = consent.

We're good to go!

**Comment by hackmastera** [comment]
When we push the code, the UI will appear to lose the values on title / description fields after the first value. However, that's just the UI. Once we run the rake tasks the data will be migrated over and everything will look right.

**Comment by hackmastera** [comment]
1. Activate maintenance mode
2. deploy the new code
3. run the two rake tasks
  1. RAILS_ENV=production bundle exec rake chf:migrate_titles
  1. RAILS_ENV=production bundle exec rake chf:combine_descriptions
4. turn off maintenance mode

**Comment by hackmastera** [comment]
Hm, should've written those two rake tasks in one to save time. oh, well.

**Comment by hackmastera** [comment]
staging migration started around 3:20. here are some works we can look at for description combination: 

- r494vk17h: 1 titles, 2 descriptions
- fj236210v: 1 titles, 1 descriptions
- 765371328: 1 titles, 2 descriptions
- rb68xb856: 1 titles, 2 descriptions
- z316q1572: 1 titles, 1 descriptions
- g158bh28p: 1 titles, 1 descriptions
- sf268508b: 1 titles, 2 descriptions
- wp988j80x: 1 titles, 2 descriptions
- hq37vn56b: 1 titles, 2 descriptions
- 4q77fr32b: 1 titles, 2 descriptions
- vt150j246: 1 titles, 2 descriptions
- gx41mh844: 1 titles, 2 descriptions
- vx021f09b: 1 titles, 1 descriptions
- 4j03cz64w: 1 titles, 1 descriptions
- c534fn92g: 1 titles, 1 descriptions
- m326m176h: 1 titles, 1 descriptions
- 8w32r5659: 1 titles, 2 descriptions
- qz20ss53m: 1 titles, 2 descriptions
- ht24wj46b: 1 titles, 2 descriptions
- 9w0323064: 1 titles, 2 descriptions
- 0c483j470: 1 titles, 1 descriptions
- 41687h49p: 1 titles, 2 descriptions
- dz010q13w: 1 titles, 2 descriptions
- 3b591864x: 1 titles, 2 descriptions

and title reshuffling:

- 2z10wq27b: 2 titles, 1 descriptions
- 1544bp19x: 2 titles, 1 descriptions

**Comment by hackmastera** [comment]
it took just under an hour, but I did make another optimization which will help (it was saving when there were no descriptions)

**Comment by hackmastera** [comment]
Pushed the new ordering code and ran the update this morning.
